apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: errcmd/python_producer:0.4
        env:
        - name: KAFKA_SERVICE
          value: "kf-kafka"
        ports:
        - containerPort: 8000
          name: metrics
          protocol: TCP
