#!/bin/bash

set -euo pipefail

readonly dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Distclean is executing now..."

pushd "${dir}/../"
trap 'popd' EXIT

rm -vfr tools/*

rm -vf certificates/*pem
rm -vf certificates/*csr

rm -vf config/*kubeconfig
rm -vf config/worker-*
rm -vf config/controller-*


rm -vf /usr/local/bin/cfssl
rm -vf /usr/local/bin/cfssljson
rm -vf /usr/local/bin/kubectl
