#!/bin/bash

set -euo pipefail

readonly dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Generate-certs/generate-ca is executing now"

pushd "${dir}/../certificates"
trap 'popd' EXIT

cfssl gencert -initca ca-csr.json | cfssljson -bare ca
